### ISSUE TITLE
TypeError: Cannot read property 'update' of undefined

### ISSUE THREAD

**Issue by AndyOGo** [lmtm/node-sync-files#5]
The `configstore` randomly throws this error.

``` sh
  .../node_modules/configstore/index.js:86
    return this.all[key];
                   ^

 TypeError: Cannot read property 'update' of undefined
     at Object.Configstore.get (.../node_modules/configstore/index.js:86:17)
     at UpdateNotifier.check (.../node_modules/update-notifier/index.js:51:28)
     at module.exports (.../node_modules/update-notifier/index.js:127:17)
     at Object.<anonymous(.../node_modules/sync-files/bin/sync-files.js:121:3)
     at Module._compile (module.js:413:34)
     at Object.Module._extensions..js (module.js:422:10)
     at Module.load (module.js:357:32)
     at Function.Module._load (module.js:314:12)
     at Function.Module.runMain (module.js:447:10)
     at startup (node.js:146:18)
```

**Comment by AndyOGo** [comment]
@naholyr 
Hello, do you have any chance to look into this one?

**Comment by AndyOGo** [comment]
This bug can be "disabled" by setting `--no-notify-update`

**Comment by wamoyo** [comment]
@AndyOGo Any luck? I've had this issue for years. Perhaps it's from a different module? 'update-notifier' perhaps? https://github.com/yeoman/update-notifier/issues 

Can't seem to track it down.

**Comment by AndyOGo** [comment]
@wamoyo 
Yes, it's an `update-notifier` issue.
