### ISSUE TITLE
TypeError: Cannot read property 'optOut' of undefined

### ISSUE THREAD

**Issue by AndyOGo** [lmtm/node-sync-files#6]
The `configstore` randomly throws this error.

``` sh
.../node_modules/sync-files/node_modules/configstore/index.js:86
    return this.all[key];
                   ^
TypeError: Cannot read property 'optOut' of undefined
    at Object.Configstore.get (.../node_modules/sync-files/node_modules/configstore/index.js:86:17)
    at UpdateNotifier.check (.../node_modules/sync-files/node_modules/update-notifier/index.js:47:18)
    at module.exports (.../node_modules/sync-files/node_modules/update-notifier/index.js:127:17)
    at Object.<anonymous> (.../node_modules/sync-files/bin/sync-files.js:121:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
```

**Comment by AndyOGo** [comment]
This bug can be "disabled" by setting `--no-notify-update`

**Comment by wamoyo** [comment]
I have the same issue. It only happens once in a while though. What does --no-notify-update mean?

**Comment by AndyOGo** [comment]
Please see the usage secrion of the readme
https://github.com/byteclubfr/node-sync-files/blob/master/README.md#usage

**Comment by wamoyo** [comment]
Right, that's the help text. But I don't understand the relationship between that option and this error?

**Comment by wamoyo** [comment]
It's a great module, by the way! Hasn't given me any other problems ever : ) Even this occasional error messages isn't really a problem, just kind of confusing. Can't tell why it's coming up, or why it only happens sometimes.

**Comment by AndyOGo** [comment]
Okay.
The stack trace above tells you where it comes from.
Or just debug it if you want to know, https://github.com/byteclubfr/node-sync-files/blob/master/bin/sync-files.js#L120-L122

**Comment by AndyOGo** [comment]
btw update-notifier is another package
https://github.com/yeoman/update-notifier

**Comment by wamoyo** [comment]
Thank, man!
