### ISSUE TITLE
TypeError: Cannot read property 'lastUpdateCheck' of undefined

### ISSUE THREAD

**Issue by AndyOGo** [lmtm/node-sync-files#7]
The `configstore` randomly throws this error.

``` sh
.../node_modules/configstore/index.js:86
    return this.all[key];
                   ^
TypeError: Cannot read property 'lastUpdateCheck' of undefined
    at Object.Configstore.get (.../node_modules/configstore/index.js:86:17)
    at UpdateNotifier.check (.../node_modules/update-notifier/index.js:58:31)
    at module.exports (.../node_modules/update-notifier/index.js:127:17)
    at Object.<anonymous> (.../node_modules/sync-files/bin/sync-files.js:121:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
```

**Comment by AndyOGo** [comment]
@byteclubfr
did you had any chance to look into this?

**Comment by AndyOGo** [comment]
This bug can be "disabled" by setting `--no-notify-update`
